{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "05c8f7f9-6cdd-473a-8b26-141b34fb38a9",
   "metadata": {},
   "source": [
    "一个复杂的软件系统通常不由一个程序组成，而是由一堆程序配合工作（前端、后端、数据库、缓存...）。\n",
    "\n",
    "- `docker compose up` 时，它就会乖乖地把这些全部拉起来。\n",
    "    - `compose.yml`\n",
    "        - `services`\n",
    "            - `frontend`\n",
    "            - `backend`\n",
    "        - `volumes`"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "27c37548-dac3-4cb3-86e8-d699a43bbb0b",
   "metadata": {},
   "source": [
    "### compse.yml"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1b03ae88-ea43-467c-a7c1-3c0ebcdcfc9f",
   "metadata": {},
   "source": [
    "```yml\n",
    "services:\n",
    "  frontend:\n",
    "    network_mode: host\n",
    "  backend:\n",
    "    network_mode: host\n",
    "  redis-for-backend:\n",
    "    network_mode: host\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "63d0a759-489c-4566-9ba2-23e950cf2915",
   "metadata": {},
   "source": [
    "### verl docker(file)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2b03022e-2657-4f27-a626-4b18bdda0315",
   "metadata": {},
   "source": [
    "- https://github.com/verl-project/verl/blob/main/docker/Dockerfile.stable.vllm"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "verl",
   "language": "python",
   "name": "verl"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
